Vagrant.configure("2") do |config|
  config.vm.box = "wheezy64"
  config.vm.box_url = "https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/host"
  config.vm.network "forwarded_port", guest: 5050, host: 5050
  config.vm.define "homekiserver" do |t|
  end
  config.vm.provider "virtualbox" do |v| 
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
