Vagrant.configure("2") do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.box_version = "7.9.1"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/host"
  config.vm.network "forwarded_port", guest: 5050, host: 5050 # remote debugger
  config.vm.network "forwarded_port", guest: 5000, host: 5000 # homeki web
  config.vm.network "forwarded_port", guest: 5432, host: 5432 # postgres
  config.vm.define "homekiserver" do |t|
  end
  config.vm.provider "virtualbox" do |v| 
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ['modifyvm', :id, '--usb', 'on']
    v.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'aeonzstick', '--vendorid', '0x10c4', '--productid', '0xea60']
  end
end
