#!/bin/bash

set -e

if [ "$1" = "configure" ] ; then
	DBUSER=root
	DBPASS=homeki
	HDBUSER=homeki
	HDBPASS=homeki
	START=yes

	echo -n "creating homeki user: "
	if [ "X`grep "^homeki:" /etc/passwd`" == "X" ]; then
		useradd --home-dir /home/homeki --create-home --groups admin,plugdev homeki
		echo "done"
	else
		echo "not needed, already exists"
	fi
	
	# needed because mysql commands rely on fail exit codes to determine what to do
	set +e
	
	echo -n "connecting to mysql: "
	echo "exit" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
	
	if [ $? -ne 0 ]; then
		echo "connection failed, manual database setup needed"
		START=no
	else
		echo "done"
	
		echo -n "creating mysql homeki user: "
		echo "SELECT User FROM mysql.user WHERE User = 'homeki'" | mysql --user=$DBUSER --password=$DBPASS | grep homeki > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "CREATE USER '$HDBUSER'@'localhost' IDENTIFIED BY '$HDBPASS'" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
			echo "done"
		else
			echo "not needed, already exists"
		fi
	
		echo -n "creating mysql homeki database: "
		echo "SHOW DATABASES" | mysql --user=$DBUSER --password=$DBPASS | grep homeki > /dev/null 2>&1
	        if [ $? -ne 0 ]; then
	                echo "CREATE DATABASE homeki" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
			echo "done"
		else
			echo "not needed, already exists"
	        fi
	
		echo "GRANT ALL ON homeki.* TO 'homeki'@'localhost'" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
	fi
	
	set -e
	
	echo -n "changing owner of /mnt/1wire: "
	if [ -d /mnt/1wire ]; then
		chown -R homeki:homeki /mnt/1wire
		echo "done"
	else
		echo "does not exist"
	fi

	echo -n "changing owner and permissions in /opt/homeki: "
	chown -R homeki:homeki /opt/homeki
	chmod a+w /opt/homeki/stdout.log
	chmod a+w /opt/homeki/stderr.log
	echo "done"
	
	echo -n "adding S99homeki symlink to runlevel 2: "
	ln -sf /etc/init.d/homekid /etc/rc2.d/S99homeki
	echo "done"
	
	if [ $START == "yes" ]; then
		echo "------------------- APT: STARTED HOMEKI -------------------" >> /opt/homeki/stdout.log
		/etc/init.d/homekid start
	fi
fi

exit 0
