#!/bin/sh

set -e

if [ "$1" = "install" ] ; then
	mkdir -p /opt/homekey
	touch /opt/homekey/homekey.db
	touch /opt/homekey/stdout.log
	touch /opt/homekey/stderr.log
fi

if [ "$1" = "upgrade" ] ; then
	/etc/init.d/homekeyd stop
fi

exit 0
