#!/bin/sh

set -e

if [ "$1" = "install" ] ; then
	mkdir -p /opt/homeki
	touch /opt/homeki/homeki.db
	touch /opt/homeki/stdout.log
	touch /opt/homeki/stderr.log
fi

if [ "$1" = "upgrade" ] ; then
	/etc/init.d/homekid stop
fi

exit 0
