#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	/etc/init.d/homekeyd stop
	rm -f /opt/homekey/stdout.log
	rm -f /opt/homekey/stderr.log
	rm -f /opt/homekey/homekey.pid
	mkdir -p /home/homekey
	mv -f /opt/homekey/homekey.db /home/homekey/`date +%Y%m%d-%H%M%S`-homekey.db
fi

exit 0
ail