#!/bin/bash

set -e

if [ "$1" = "remove" ] ; then
	/etc/init.d/homekid stop
	
	echo -n "removing log files: "
	rm -f /opt/homeki/stdout.log
	rm -f /opt/homeki/stderr.log
	rm -f /opt/homeki/homeki.pid
	rm -rf /opt/homeki/log
	echo "done"
	
	update-rc.d homekid remove
fi

exit 0
